name: Deploy Backend & Frontend

on:
  push:
    branches:
      - dev
      - staging


jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Login to ECR
        run: |
          aws ecr get-login-password --region ap-south-1 \
          | docker login --username AWS --password-stdin 121861012711.dkr.ecr.ap-south-1.amazonaws.com



      - name: Build Docker Image
        run: docker build -f ./backend/Dockerfile -t backend-app ./backend

      - name: Tag Docker Image
        run: docker tag backend-app:latest 121861012711.dkr.ecr.ap-south-1.amazonaws.com/backendapp:latest

      - name: Push Docker Image
        run: docker push 121861012711.dkr.ecr.ap-south-1.amazonaws.com/backendapp:latest

      - name: Set Environment
        run: |
          if [[ "${GITHUB_REF_NAME}" == "dev" ]]; then
            echo "ENV=dev" >> $GITHUB_ENV
            echo "TF_VAR_env=dev" >> $GITHUB_ENV
            echo "FRONTEND_URL=https://d2b4juob8ltmwr.cloudfront.net" >> $GITHUB_ENV
          else
            echo "ENV=staging" >> $GITHUB_ENV
            echo "TF_VAR_env=staging" >> $GITHUB_ENV
            echo "FRONTEND_URL=https://d3umkbb4uop226.cloudfront.net" >> $GITHUB_ENV
          fi
      - name: Debug Terraform path
        run: |
          echo "ENV=$ENV"
          ls -R infrastructure
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.7


      - name: Terraform Init
        run: terraform init
        working-directory: infrastructure/${{ env.ENV }}

      - name: Terraform Apply
        run: terraform apply -auto-approve
        working-directory: infrastructure/${{ env.ENV }}


      - name: Build Frontend
        run: |
          cd frontend
          npm install
          npm run build
        env:
          NEXT_PUBLIC_API_URL: ${{ env.FRONTEND_URL }}
          
          
#####################
      - name: Sync Frontend to S3
        run: aws s3 sync ./frontend/out/ s3://pg-agi-frontend-env-${{ env.ENV }}/ --delete