name: Deploy Backend & Frontend

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Login to ECR
        run: |
          aws ecr get-login-password --region ap-south-1 \
          | docker login --username AWS --password-stdin 314103481823.dkr.ecr.ap-south-1.amazonaws.com

      - name: Build Docker Image
        run: docker build -f ./backend/Dockerfile -t backend-app ./backend

      - name: Tag Docker Image
        run: docker tag backend-app:latest 314103481823.dkr.ecr.ap-south-1.amazonaws.com/backend-app:latest

      - name: Push Docker Image
        run: docker push 314103481823.dkr.ecr.ap-south-1.amazonaws.com/backend-app:latest

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.7

      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply
        run: terraform apply -auto-approve


      - name: Build Frontend
        run: |
          cd frontend
          npm install
          npm run build
          npm run export

      - name: Sync Frontend to S3
        run: aws s3 sync ./frontend/out/ s3://pg-agi-frontend-dev/ --delete